# wordpress-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: wordpress_root_password
  MYSQL_PASSWORD: wordpress_password
  WORDPRESS_DB_PASSWORD: wordpress_password