---
- hosts: wordpress_servers
  become: yes
  vars:
    prometheus_version: "v2.30.3"
    grafana_version: "8.1.5"
    alertmanager_version: "0.23.0"

  tasks:
    - name: Create monitoring directory
      file:
        path: /opt/monitoring
        state: directory
        mode: 0755

    - name: Pull Prometheus Docker image
      docker_image:
        name: prom/prometheus:{{ prometheus_version }}
        source: pull

    - name: Pull Grafana Docker image
      docker_image:
        name: grafana/grafana:{{ grafana_version }}
        source: pull

    - name: Pull Alertmanager Docker image
      docker_image:
        name: prom/alertmanager:{{ alertmanager_version }}
        source: pull

    - name: Create Prometheus configuration
      copy:
        dest: /opt/monitoring/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          
          scrape_configs:
            - job_name: 'wordpress'
              static_configs:
                - targets: ['localhost:9090']
            
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']

    - name: Create Docker Compose file for monitoring
      copy:
        dest: /opt/monitoring/docker-compose.yml
        content: |
          version: '3'
          services:
            prometheus:
              image: prom/prometheus:{{ prometheus_version }}
              volumes:
                - ./prometheus.yml:/etc/prometheus/prometheus.yml
              ports:
                - "9090:9090"
              restart: always

            grafana:
              image: grafana/grafana:{{ grafana_version }}
              ports:
                - "3000:3000"
              volumes:
                - grafana_data:/var/lib/grafana
              restart: always

            node_exporter:
              image: prom/node-exporter:latest
              ports:
                - "9100:9100"
              restart: always

            alertmanager:
              image: prom/alertmanager:{{ alertmanager_version }}
              ports:
                - "9093:9093"
              restart: always

          volumes:
            grafana_data:

    - name: Start monitoring services
      docker_compose:
        project_src: /opt/monitoring
        state: present