name: WordPress Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Build WordPress Docker Image
      run: |
        eval $(minikube docker-env)
        docker build -t wordpress-custom:latest .
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/wordpress-secrets.yaml
        kubectl apply -f k8s/mysql-pvc.yaml
        kubectl apply -f k8s/wordpress-pvc.yaml
        kubectl apply -f k8s/mysql-deployment.yaml
        kubectl apply -f k8s/mysql-service.yaml
        kubectl apply -f k8s/wordpress-deployment.yaml
        kubectl apply -f k8s/wordpress-service.yaml
    
    - name: Wait for deployment
      run: |
        kubectl rollout status deployment/wordpress
        kubectl rollout status deployment/mysql
    
    - name: Port forward for testing
      run: |
        kubectl port-forward service/wordpress 8080:80 &
        sleep 10
        curl http://localhost:8080