name: WordPress CI/CD Deployment
on:
  push:
    branches:
      - main

jobs:
  trigger-terraform:
    uses: .github/workflows/terraform-deploy.yml
  
  trigger-ansible:
    needs: trigger-terraform
    uses: .github/workflows/ansible-configure.yml