name: WordPress CI/CD Deployment
on:
  push:
    branches:
      - main

jobs:
  trigger-terraform:
    uses: ./.github/workflows/terraform-deploy.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  trigger-ansible:
    needs: trigger-terraform
    uses: ./.github/workflows/ansible-configure.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}